/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as ErpRouteImport } from './routes/erp'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const ErpRoute = ErpRouteImport.update({
  id: '/erp',
  path: '/erp',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/erp': typeof ErpRoute
  '/fees': typeof FeesRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/erp': typeof ErpRoute
  '/fees': typeof FeesRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/erp': typeof ErpRoute
  '/fees': typeof FeesRoute
  '/login': typeof LoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/contact'
    | '/erp'
    | '/fees'
    | '/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/contact'
    | '/erp'
    | '/fees'
    | '/login'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/contact'
    | '/erp'
    | '/fees'
    | '/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicsRoute: typeof AcademicsRoute
  AdmissionsRoute: typeof AdmissionsRoute
  ContactRoute: typeof ContactRoute
  ErpRoute: typeof ErpRoute
  FeesRoute: typeof FeesRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erp': {
      id: '/erp'
      path: '/erp'
      fullPath: '/erp'
      preLoaderRoute: typeof ErpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicsRoute: AcademicsRoute,
  AdmissionsRoute: AdmissionsRoute,
  ContactRoute: ContactRoute,
  ErpRoute: ErpRoute,
  FeesRoute: FeesRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
